# Generated by Django 2.1.2 on 2019-02-14 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_supportedresourcetype_patch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerouter',
            name='supported_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.SupportedResourceType'),
        ),
    ]
